baseURL = 'https://darren-adlink.github.io/CPL64V/'
languageCode = 'zh-tw'
title = 'CPL64V 相機相容性 Portal'
theme = 'ananke'

[params]
  description = 'CPL64V 與各品牌相機參數對應中心'
  images = ["images/og-image.png"]

[[menu.main]]
  name = '首頁'
  url = '/'
  weight = 1

[[menu.main]]
  name = '相機參數 Portal'
  url = '/camera-portal/'
  weight = 2

[[menu.main]]
  name = '學習紀錄'
  url = '/worklog/'
  weight = 3
